export const MEMBER_LOGIN = 'MEMBER_LOGIN';
export const MEMBER_LOGOUT = 'MEMBER_LOGOUT';
export const MEMBER_LOAD_AUTH = 'MEMBER_LOAD_AUTH';
export const MEMBER_GET_MY_ARTICLES = 'MEMBER_GET_MY_ARTICLES';