export const ARTICLE_GET_LATEST = 'ARTICLE_GET_LATEST';
export const ARTICLE_GET_SEARCH_RESULTS = 'ARTICLE_GET_SEARCH_RESULTS';
export const ARTICLE_GET_BY_ID = 'ARTICLE_GET_BY_ID';
export const ARTICLE_GET_RELATED_ARTICLES = 'ARTICLE_GET_RELATED_ARTICLES';
export const ARTICLE_ACTIVE_RESET = 'ARTICLE_ACTIVE_RESET';

export const ARTICLE_CREATE = 'ARTICLE_CREATE';
export const ARTICLE_EDIT_BY_ID = 'ARTICLE_EDIT_BY_ID';
export const ARTICLE_UPDATE_BY_ID = 'ARTICLE_UPDATE_BY_ID';
export const ARTICLE_DELETE_BY_ID = 'ARTICLE_DELETE_BY_ID';